# Generated by Django 3.2.3 on 2021-06-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieposter',
            old_name='photo',
            new_name='poster',
        ),
        migrations.AddField(
            model_name='movieposter',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
