# Generated by Django 3.2.3 on 2021-06-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20210604_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoviePoster',
            new_name='Movie',
        ),
    ]
